### ISSUE TITLE
[1.9] Updating from 2.0.8 to 2.0.9 crash

### ISSUE THREAD

**Issue by b0bst3r** [ZAZPRO/BaublesStuff#1]
Also it seemed those without any bauble in couldn't hit anything, not passive animals or mobs.  Everytime someone tried it caused pages of crashes in the server console which eventually caused the crash below.

http://pastebin.com/cwE6edhe

Forge 1907
Baublestuff 2.0.9

**Comment by ZAZPRO** [comment]
Fixed!
