### ISSUE TITLE
LivingHurtEvent errors without Pendant_Core

### ISSUE THREAD

**Issue by DreamingLamb** [ZAZPRO/BaublesStuff#2]
I'm not 100% sure if it's your mod causing the issue, but if player's aren't wearing your Pendant_Core on my server, they're unable to damage any mobs.  Once they're wearing the pendant, everything works as normal.

There are errors produced on the console: http://pastebin.com/N5w5hwqh

**Comment by ZAZPRO** [comment]
Fixed!
