### ISSUE TITLE
Resurgence of console spam in 1.9.4 when combined with BoP

### ISSUE THREAD

**Issue by Gunner76th** [ZAZPRO/BaublesStuff#5]
Just wanted to cross post the issue thread from the Curse page to your github repo for tracking purposes. In release 2.0.10 the following console spam on clients has returned:

'[biomesoplenty.common.world.WorldChunkManagerBOP:<init>:67]: settings for world: ' and '[biomesoplenty.common.world.WorldChunkManagerBOP:initialLandAndSeaLayer:99]: Setting up landmass VANILLA '

This was originally reported in issue #11 on Curse http://minecraft.curseforge.com/projects/baubles-stuff/issues/11

**Comment by ZAZPRO** [comment]
Check new version. Fixed!
